export const works = [
  {
    title: "Forecoms 35 years anniversary",
    images: [
      "/forecoms/fore1.webp",
      "/forecoms/fore2.webp",
      "/forecoms/fore3.webp",
      "/forecoms/fore4.webp",
      "/forecoms/fore5.webp",
      "/forecoms/fore6.webp",
    ],
    id: "forecoms",
    Subtitle: "Total Event Production & Management by HQ Entertainment",
    secondaryTitle: "",
    year: "2024",
  },
  {
    title: "Tribute to Legend concerts ",
    images: [
      "/tribute/tr1.webp",
      "/tribute/tr2.webp",
      "/tribute/tr3.webp",
      "/tribute/tr4.webp",
      "/tribute/tr5.webp",
    ],
    id: "tribute-to-legend-concerts",
    Subtitle: "Total Event Production & Management by HQ Entertainment",
    secondaryTitle: "Chandimal Fernando",
    year: "2024",
  },
  {
    title: "Sadde Music Video",
    images: [
      "/sadee/sa1.webp",
      "/sadee/sa2.webp",
      "/sadee/sa3.webp",
      "/sadee/sa4.webp",
      "/sadee/sa5.webp",
      "/sadee/sa6.webp",
    ],
    id: "sadde-music-video",
    Subtitle: "LED Screen Production & Management by HQ Entertainment",
    secondaryTitle: "Lahiru Perera",
    year: "2024",
  },
  {
    title: "Helakuru Annual General Meeting ",
    images: ["/helakuru/he1.webp", "/helakuru/he2.webp", "/helakuru/he3.webp"],
    id: "helakuru",
    Subtitle: "LED Screen Production & Management by HQ Entertainment",
    secondaryTitle: "AGM",
    year: "2023",
  },
  {
    title: "Spa Ceylon Immersive Experience",
    images: [
      "/spa/spa.webp",
      "/spa/sap2.webp",
      "/spa/spa3.webp",
      "/spa/spa4.webp",
      "/spa/spa5.webp",
      "/spa/spa6.webp",
      "/spa/spa7.webp",
      "/spa/spa8.webp",
      "/spa/spa9.webp",
    ],
    id: "spa-ceylon",
    Subtitle: "LED Screen Production & Management by HQ Entertainment",
    secondaryTitle: "",
    year: "2024",
  },
];
export default works;
